[opener]
edit = [
    { run = 'nvim "%*"', block = true, desc = "Neovim", for = "windows" },
]
py_run = [
    # run: запускает python, передает файл (%1) и ставит паузу в конце
    # block = true: скрывает интерфейс Yazi и показывает терминал
    { run = 'cmd /c "python "%1" & pause"', block = true, desc = "Run Python", for = "windows" }
]

[open]
prepend_rules = [
    { name = "*.py", use = "py_run" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# Шаг 1: Описываем сами программы (openers)
[[opener.pdf-zathura]]
run = "zathura \"$@\""
desc = "Открыть в Zathura"

[[opener.pdf-okular]]
run = "okular \"$@\""
desc = "Открыть в Okular"

# Шаг 2: Привязываем программы к PDF-файлам
[[open.rules]]
mime = "application/pdf"
use = [ "pdf-zathura", "pdf-okular", "reveal" ]
